<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PriceSentinel3000.Application\PriceSentinel3000.Application.csproj" />
    <ProjectReference Include="..\PriceSentinel3000.Core\PriceSentinel3000.Core.csproj" />
    <ProjectReference Include="..\PriceSentinel3000.Infrastructure\PriceSentinel3000.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
